version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file: '.env'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./resources/database_backup.sql:/docker-entrypoint-initdb.d/database_backup.sql
volumes:
  postgres_data:
    driver: local
